import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import ClientNavbar from "@/helpers/LoginNavbarNull";
import type { Metadata } from "next";
import ClientFooter from "@/helpers/LoginFooterNull";
import React from "react";


const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Time makes difference",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/watch2.png" />
      </head>
      <body className={josefinSans.className}>
        <ClientNavbar />
        {children}
        <ClientFooter />
      </body>
    </html>
  );
}
