import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import ClientNavbar from "@/helpers/LoginNavbarNull";
import type { Metadata } from "next";
import ClientFooter from "@/helpers/LoginFooterNull";
import React, { Suspense } from "react";
import Loading from "./loading";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={josefinSans.className}>
        <Suspense fallback={<Loading />}>
          <ClientNavbar />
          {children}
          <ClientFooter />
        </Suspense>
      </body>
    </html>
  );
}
